### ISSUE TITLE
Couldn't find package "@canner/customize-string-input@^0.1.18"

### ISSUE THREAD

**Issue by aalibaabaa** [CannerCMS/cannercms#106]
Hi folks,

I tried to install canner client by running `npm install -g @canner/cli`. Seems, that there is a missing dependency. I get the error message `Couldn't find package "@canner/customize-string-input@^0.1.18" required by "@canner/cli"`

Could you please check that?

**Comment by chilijung** [comment]
Hey @aalibaabaa, may I ask which version are you trying to install 1.5.0-canary.x version is not officially public yet. But I've just public the package, you can try reinstall thanks!

**Comment by chilijung** [comment]
Oh never mind, forget what I said. I think we have published a new public version in CLI which cause the error that you mentioned.
