### ISSUE TITLE
How to store files on local filesystem

### ISSUE THREAD

**Issue by jacargentina** [CannerCMS/cannercms#113]
I'm starting to learn about canner; i've found that for file uploads there is `FirebaseClientStorage` https://www.canner.io/docs/guides-storage

My files are my data too, so i would like to migrate my website from keystone to canner, but can't find there is some storage for files on my server itself ? Maybe i'm missing something.

**Comment by chilijung** [comment]
Hi @jacargentina, could you tell us more about your use cases

> My files are my data

Does this mean that you are trying to use Canner CMS to manage data from your local server?

Thanks.

**Comment by jacargentina** [comment]
@chilijung exactly. I want to upload files in my very own server

**Comment by chilijung** [comment]
Unfortunately. Currently, Canner is focused on supporting cloud services & specific BaaS servers. We are supporting Firebase/Firestore, Prisma servers.

Local storage is not available on Canner now. Thanks!

**Comment by jacargentina** [comment]
@chilijung so please, modify https://www.canner.io/docs/guides-storage

Would be nice to make it clear: for Canner, **files are not your data**, files are **cloud services & specific BaaS servers** data. **NOT yours**

**Comment by chilijung** [comment]
@jacargentina added in docs, will update next publish thanks.
