### ISSUE TITLE
cli: No such file or directory

### ISSUE THREAD

**Issue by 11111000000** [CannerCMS/cannercms#118]
```
~/.npm/lib/node_modules/@canner/cli/download/dist]$ ldd ./cli
        linux-vdso.so.1 (0x00007ffecc5ec000)
        libdl.so.2 => /nix/store/i6kzbaaac0ppjab1230i70wdaz9klwl6-glibc-2.27/lib/libdl.so.2 (0x00007efe4f1f9000)
        librt.so.1 => /nix/store/i6kzbaaac0ppjab1230i70wdaz9klwl6-glibc-2.27/lib/librt.so.1 (0x00007efe4eff1000)
        libstdc++.so.6 => not found
        libm.so.6 => /nix/store/i6kzbaaac0ppjab1230i70wdaz9klwl6-glibc-2.27/lib/libm.so.6 (0x00007efe4ec60000)
        libgcc_s.so.1 => not found
        libpthread.so.0 => /nix/store/i6kzbaaac0ppjab1230i70wdaz9klwl6-glibc-2.27/lib/libpthread.so.0 (0x00007efe4ea42000)
        libc.so.6 => /nix/store/i6kzbaaac0ppjab1230i70wdaz9klwl6-glibc-2.27/lib/libc.so.6 (0x00007efe4e68b000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/i6kzbaaac0ppjab1230i70wdaz9klwl6-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007efe4f3f
d000)                                                                                                        
```

**Comment by 11111000000** [comment]
(nixos lastest)

**Comment by abz53378** [comment]
Hi, @11111000000 , thanks for the report.
Does the installation process well or any error occurs? And If you enter `canner` command, what's the error thrown? Thanks!

**Comment by 11111000000** [comment]
There is no any errors, until `canner`:
`No such file or directory`

**Comment by abz53378** [comment]
Thanks for the response, I found the reason is that `nixos` doesn't support executing binary files by default. You can see the official documentation [here](https://nixos.wiki/wiki/Packaging/Binaries).

**Comment by 11111000000** [comment]
I know that :)  So, you want to package canner everywhere? 2) How about working `Dockerfile` example?

**Comment by abz53378** [comment]
Sounds great! We plan to use [node-docker](https://github.com/nodejs/docker-node) as the image, does it fit your needs?

**Comment by 11111000000** [comment]
it's ok for example, in practice we based on node-alpine

**Comment by abz53378** [comment]
Here is the basic `Dockerfile` and `canner.schema.js`. *But notice that the command `canner script:serve` is designed to preview the CMS when developing.*  The correct way to host Canner CMS is using `canner script:deploy` to deploy the `schema` and `canner.cloud.js` to our platform.

Please let me know whether this fit your needs, thanks!

**Directory**
```
|- Dockerfile
|- schema
   |- canner.schema.js
```
**Dockerfile**
```
FROM node:6
RUN npm install -g @canner/cli
WORKDIR /schema
COPY ./schema /schema
EXPOSE 80
CMD ["canner", "script:serve", "/schema/canner.schema.js", "--host", "0.0.0.0", "--port", "80"]
```

**canner.schema.js**
```js
/** @jsx builder */
import builder from 'canner-script'

export default (
  <root>
    <object keyName="info">
      <string keyName="name" />
    </object>
  </root>
)
```

**Comment by FeklistovGleb** [comment]
Hello. When use traefik to proxy request to container with canner, response contain "Invalid Host header", traefik compression if off, when request send direct to container all right. Where problem?

**Comment by abz53378** [comment]
Hi, @FeklistovGleb, since we are using `webpack-dev-server` in `canner script:serve` for developing, the problem relates to the [option](https://webpack.js.org/configuration/dev-server/#devserver-disablehostcheck). So I will add it soon and Inform you after new CLI releases. Thanks.

**Comment by FeklistovGleb** [comment]
> Hi, @FeklistovGleb, since we are using `webpack-dev-server` in `canner script:serve` for developing, the problem relates to the [option](https://webpack.js.org/configuration/dev-server/#devserver-disablehostcheck). So I will add it soon and Inform you after new CLI releases. Thanks.

Thanks. This issue is closed.

**Comment by FeklistovGleb** [comment]
canner static:build - command not found? Where this usage? Maybe command removed from last version canner?

**Comment by 11111000000** [comment]
> Hi, @FeklistovGleb, since we are using `webpack-dev-server` in `canner script:serve` for developing, the problem relates to the [option](https://webpack.js.org/configuration/dev-server/#devserver-disablehostcheck). So I will add it soon and Inform you after new CLI releases. Thanks.

@abz53378  How avoid this with current cli or we can use own cli?

**Comment by abz53378** [comment]
Try using `@canner/cli@2.6.3`, you can use `canner script:serve -d, --disable-host-check` to ignore the host check. This option just a quick fix for the `script:serve`, we will support the `static:build` and `start` commands for production usage (#126 ) soon. There will be more options that I think can fit most needs.

Thanks!

**Comment by abz53378** [comment]
Close this. The origin problem is resolved.
