### ISSUE TITLE
Network error: request error at connector

### ISSUE THREAD

**Issue by odifek** [CannerCMS/cannercms#130]
Please what is your take about this error? I've waded through all the errors. I am now hooked at this one.
This is my connector initialization 
```
import {FirestoreClientConnector} from 'canner-graphql-interface';
exports.connector = new FirestoreClientConnector({
    projectId: "wccrmph-church-app"
  });
  
```
After deploying, cms spits out errors 

> POST https://backend.canner.io/connector 500 (Internal Server Error)

Please what do I need to do to fix this?

**Comment by abz53378** [comment]
Hi, @odifek, `FirebaseClientConnector` only work for community version which means you build the CMS with our `<Canner >` component in a react project. (see [the code of demo](https://github.com/Canner/canner/blob/canary/docs/index.js))

On our platform, we provide the file `canner.cloud.js` for developers to deploy the credential files, so you don't have to declare the `connector` in your schema, just create a `canner.cloud.js` like the docs [here](https://www.canner.io/docs/credential-firebase).

Thanks!

**Comment by odifek** [comment]
Oh thank you very much. I will try that out and revert

**Comment by odifek** [comment]
So great, I removed the connector and everything works fine now except for storage. It's still says 

> There is no storage config so you can't upload image. Checkout the storage section to know more

**Comment by odifek** [comment]
I finally solved the above by inserting the imageStorage attribute in the root tag instead
