### ISSUE TITLE
Import Data err: Reading canner.cloud.js occurs errors.

### ISSUE THREAD

**Issue by imakou** [CannerCMS/cannercms#137]
Hi All,

I am facing that the data cannot be loaded from firebase.
By using cli `canner data:import`, I got the error msg 
```
Reading canner.cloud.js occurs errors. Error: Plugin 0 specified in "base" provided an invalid property of "default"
```
`canner.cloud.js`
```
env: {
    default: [new FirebaseCredential(require("./cert.json"))]
  },
```

`canner.scheme.js`
```
export default (
  <root>
    <object keyName="header" title="Main page">
      <string keyName="icon" title="Website icon" />
      <string keyName="title" title="Website title" />
      ...
  </root>
}
```
Should I configure `canner.scheme.js`?
I don't modify `canner.scheme.js` too much, just following the format since it was initialized.

Any suggestion?
Thanks.

**Comment by abz53378** [comment]
Hi, @imakou, `canner data:import` is used to import your fake data(written in `canner.data.json`) into your `firebase`, and if you want to load the data from 'firebase', you can use the the command `canner script:serve --env default`, thanks!
