### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by wwwy3y3** [CannerCMS/cannercms#144]
## Official docker image for canner-server
We'll use multi-stage docker image (https://docs.docker.com/develop/develop-images/multistage-build/) to build the static files first, and serve it at next image.

There are still some bundle issues we need to resolve. After resolving issues, we'll push images to docker hub for everyone to use.

**Comment by PostPollux** [comment]
Can't wait for this to happen! Keep it up!

**Comment by chilijung** [comment]
Hi @PostPollux, you can check out document https://www.cannercms.com/docs/guides-deployment-of-docker . you can deploy using Docker now!
