### ISSUE TITLE
Can't init Canner with no template

### ISSUE THREAD

**Issue by tpiros** [CannerCMS/cannercms#161]
**Describe the bug**
Can't init with no template - is this the expected behaviour?

**To Reproduce**
```
canner init
  Initializing...
? What template do you want to create? None
✖ File or directory '/**/repo/packages/cli/dist/schema/none/canner.schema.js' was not included into executable at compilation stage. Please recompile adding it as asset or script.
```

**Expected behavior**
Initialisation of Canner.

**Dependencies (please complete the following information):**
 - OS: [e.g. iOS] Mac OS X
 - Browser [e.g. chrome, safari] N/A
 - Node Version [e.g. 10.0.0]  v10.15.0
 - Canner Version [e.g. 3.1.0] 3.2.12

**Additional context**

**Comment by abz53378** [comment]
Hi, @tpiros, thanks for the report. Already fixed in `@canner/cli@3.2.13`.
