### ISSUE TITLE
where to put it? another installation style. 

### ISSUE THREAD

**Issue by cerebrowang** [CannerCMS/cannercms#162]
I'm in GFW.
It do not work normal installation.
I have to find another installation style of "canner"
I download cli-3.2.13.tgz, its size 98.6 MB.
BUT
where to put it ??

**Comment by abz53378** [comment]
Hi, @singerswang, here are the steps without `npm` or `yarn` in my Macbook:

1. Download the `cli-macos.gz` from [cli-release](https://github.com/Canner/cli-release/releases)
2. Ungzip it to a folder that I created called `test-install`, so here is the path: `~/projects/test-install/cli-macos`.
3. Add the script `~/projects/test-install/index.js` that enables the binary.
    ```js
    const fs = require('fs');

    function chmod (file) {
      const s = fs.statSync(file)
      const newMode = s.mode | 64 | 8 | 1
      if (s.mode === newMode) return
      const base8 = newMode.toString(8).slice(-3)
      fs.chmodSync(file, base8)
    }

    chmod('./cli-macos');
    ```
4. Execute the script
    ```
    $ node ~/projects/test-install/index.js
    ```
5. Then you can exec `cli-macos` by type `~/projects/test-install/cli-macos`

You can also alias the command `canner` in your `~/.bashrc`, like:
```bash
alias canner='~/projects/test-install/cli-macos'
```

Hope this helps you. Thanks!

**Comment by cerebrowang** [comment]
无论如何多谢 @abz53378 的答案，尽管今天早晨04：28，中国大陆时间我又搞定普通下载安装了。😓
<img width="573" alt="屏幕快照 2019-03-24 上午4 26 35" src="https://user-images.githubusercontent.com/45531711/54871363-a9086b80-4ded-11e9-99f4-50837c95cc24.png">

**Comment by cerebrowang** [comment]
为了贡献社区，下面公布本人安装最短路径。

$ brew install node -g -s

& npm install -g @canner/cli

**Comment by abz53378** [comment]
Thanks, Singers Wang, so I closed this one.

**Comment by cerebrowang** [comment]
I have send a email to you from @x.ly 我也很 faint，不是拿这小问题可以骚扰你们。
