### ISSUE TITLE
有没有繁体中文参考？

### ISSUE THREAD

**Issue by cerebrowang** [CannerCMS/cannercms#163]
我把它转换成简体中文

**Comment by chilijung** [comment]
可以的，歡迎！文件都在此：https://github.com/Canner/docs.canner.io 。謝謝！

**Comment by singerswang** [comment]
好的。我先看看怎么着手开始，有问题再问你。

Howard Chi <notifications@github.com> 于2019年3月21日周四 下午6:48写道：

**Comment by singerswang** [comment]
时间紧迫，无法肆意挥霍，翻译任务取消。详情参见 x.ly

**Comment by singerswang** [comment]
天下天才，我要99%。因为我们有天下99%的为人父母。

**Comment by cerebrowang** [comment]
现在, 没有了

**Comment by cerebrowang** [comment]
之前看到有过的

**Comment by cerebrowang** [comment]
我找见了，是 v1，还是关了吧，太大不同
