### ISSUE TITLE
Add redirects for https://www.canner.io/docs urls

### ISSUE THREAD

**Issue by brandonkal** [CannerCMS/cannercms#164]
There are a lot of these urls around on the internet and in this repository. Adding a 301 here would help fix that experience.

**Comment by brandonkal** [comment]
Looks like this is not limited to docs as /components 404s as well.

**Comment by chilijung** [comment]
We will fix this problem today, thanks for the heads up!  The URLs are a mess right now, we are fixing it.

**Comment by chilijung** [comment]
fixed. Thanks!
