### ISSUE TITLE
parse canner schema string to jsx

### ISSUE THREAD

**Issue by charlitoro** [CannerCMS/cannercms#165]
**Parse string to jsx**
I have a string schema and I want parse to canner jsx. I have been using [react-jsx-parser](https://www.npmjs.com/package/react-jsx-parser), but don't work. is there anything to do it?

**Comment by abz53378** [comment]
Already answered on spectrum [here](https://spectrum.chat/canner/cannercms/parse-canner-schema-string-to-jsx~183dea53-5bf4-4a6e-b50d-31d012822391), so I closed this one
