### ISSUE TITLE
Unable to define directory for firebase storage

### ISSUE THREAD

**Issue by ajurcevic** [CannerCMS/cannercms#181]
Hi guys, a great tool you have built.

I'm having some issues trying to set a specific directory for files to be uploaded into Firebase Storage.

Using the 'FirebaseClientStorage' method, I do have files being saved into firebase storage but they are only going to the top root directory level.
Even when I define the 'dir' value as below it just saves it to the top directory.

The loc for the image that i want is to send the files into a 'logo' folder:
```<image keyName="image" title="Image" ui="image" uiParams={{dir: "logo/"}}/>```

It seems I can perform the uiParams of 'filename' but not the 'dir'.

cheers

**Comment by abz53378** [comment]
Hi, @ajurcevic, thanks for the report, please try using `dirname`, and remove the last `/`
```js
<image keyName="image" title="Image" ui="image" uiParams={{dirname: "logo"}}/>
// or nested folder
<image keyName="image" title="Image" ui="image" uiParams={{dirname: "logo/nested"}}/>
```
Thanks!

**Comment by ajurcevic** [comment]
works perfect, thankyou!
