### ISSUE TITLE
proposal: run tests on CI

### ISSUE THREAD

**Issue by DanielRuf** [CannerCMS/cannercms#23]
Currently there is no CI and I think it makes sense to enable Travis CI for testing commits and PR.

**Comment by wwwy3y3** [comment]
Hi, @DanielRuf Thanks for your advice! Testing with CI is already on our roadmap. We'll get to that really soon.

**Comment by abz53378** [comment]
Hi, @DanielRuf, CircleCI is added! Thanks again for you interest to Canner.
