### ISSUE TITLE
does canner support multi-site configurations?

### ISSUE THREAD

**Issue by Weej1** [CannerCMS/cannercms#28]
Hi, what it says on the tin. Can I install canner once and then have different kinds of sites run? Our is that not recommended?

**Comment by wwwy3y3** [comment]
Hi @Weej1 
Canner is not a site generator like traditional CMS (e.g., WordPress). It's an `Adaptive CMS Framework` for developers to build a CMS connecting different data sources.

For more detail about `Adaptive CMS Framework`, you can learn from here: https://www.canner.io/docs/why-adaptive-cms.html.

So, for example, you have multiple sites using different API services. Canner helps you deal with the content from all these websites in one single CMS.

Hopefully, this explanation will suffice to clear your doubts.
