### ISSUE TITLE
RouterAdaptor in CMSWrapper

### ISSUE THREAD

**Issue by abz53378** [CannerCMS/cannercms#40]
## Overview

Use `RouterAdaptor` to parse `routes`, `params` and generate the `goTo` method to `CMS` component.

### different router implementation

For now, canner ask developers to pass a [history](https://www.npmjs.com/package/history) object to let `CMS` get the `routes`, `params` and `gotTo` which are used to deal with the routing in `CMS`. 

For examples:
```js
history = {
  location: {
    pathname: '/posts/postId',
    search: '?operation=create'
  },
  push: string => void
}
// can get value 
{
  routes: ['posts', 'postId'],
  params: {
    operation: 'create'
  },
  goTo: path => push(`${baseUrl}/${path}`);
}
```

But there is maybe no `history` object if developers is not using `react-router`.

So, we need provide a interface `RouterAdapter` to deal with different router usage.

## Goals

- Users can pass a `ReactRouterAdaptor` to `CMSWrapper` to deal with the routing with `react-router`

### Proposed solution

**interface**

 ```js
interface RouterAdaptor {
    getRoutes = () => Array<string>
    getParams = () => Object
    goTo = ({pathname: string, params: Object}) => void
}
```

**usage example**
```js
//  history from react-router props
//  {
//    location: {
//      pathname: '/posts/postId1',
//      search: '?op=create&payload={"title":"Default title"}'
//    },
//    push: () => ()
// };
const {history} = this.props;
const routerAdaptor = new ReactRouterAdaptor({history});
// in render 
<CMSWrapper routeAdaptor={routeAdaptor}
    <CMS />
</CMSWrapper>
// ...
...

console.log(routerAdaptor.getRoutes()); // ['posts', 'postId1']
console.log(routerAdaptor.getParams()); // {op: 'create', payload: {title: 'Default title"}}
routerAdaptor.goTo({
  pathname: '/';
  params: {}
})
```

[current implement](https://github.com/Canner/canner/blob/master/src/components/routeProvider/ReactRouterProvider.js)

**Comment by chilijung** [comment]
@abz53378  Add why section to accentuate why we need this.

**Comment by abz53378** [comment]
After the discussion with William, there are some changes:
- props name `routerAdaptor` changes to `router`
- package name should be `@canner/router-history`
- add the default router `@canenr/router`

## Detail

### @canner/router-history

If developers already use `react-router` in their projects, they can just pass the `history` object to `@canner/router-hisotry` so that they don't have to parse `routes`, `params` etc.

**examples**

```js
// app.js

import * as React from 'react';
import ReactDOM from 'react-dom';
import {BrowserRouter as Router, Route, Switch, Redirect} from 'react-router-dom';
import CMS from './cms.js';
import Home from './home.js';
import About from './about.js';

export default class App extends React.Component {
  render() {
    return (
      <Switch>
        <Route path="/" component={Home} />
        <Route path="/about" component={About} />
        <Route path="/dashboard" component={CMS} />
        <Route path="/dashboard/:activeKey" component={CMS} />
        <Redirect to="/" />
      </Switch>
    )
  }
}

ReactDOM.render(<App />, document.getElementById('root'));

```
```js
// cms.js
import * as React from 'react';
import Canner from 'canner';
import CannerContainer from '@canner/container'; // the cms-wrapper will change name to this
import Router from '@canner/router-history';

export default class CMS extends React.Component {
  render () {
    const {history} = this.props;
    const router = new Router({
      baseUrl: '/dashboard',
      history: history
    });
    return (
      <CannerContainer
        sidebarConfig={sidebarConfig}
        navbarConfig={navbarConfig}
        router={router}
        schema={schema}
      >
        <Canner  />
      </CannerContainer>
    )
  }
}

```

As you can see, using `@canner/react-history` can easily integrate `Canner` with`react-router`.  `Canner` can control the route now because of the `push` method of `history`.

### @canner/router

But what if developers don't use react-router, or start a project yet. We should provide a simple way for them to start! `@canner/router` is the solution, it actually **new** a `history` object inside, unlike `@canner/router-history` **take** the `history` object.

**examples**
```js
// app.js
import * as React from 'react';
import ReactDOM from 'react-dom';
import Canner from 'canner';
import CannerContainer from '@canner/container'; // the cms-wrapper will change name to this
import Router from '@canner/router-history';
const router = new Router({  // this router will handle its own history object
  baseUrl: '/dashboard'
});
class App extends React.Component {
  render() {
    return (
      <CannerContainer
        sidebarConfig={sidebarConfig}
        navbarConfig={navbarConfig}
        router={router}
        schema={schema}
      >
        <Canner  />
      </CannerContainer>
    )
  }
}

```


#### Proposed Solution

Use [history](https://www.npmjs.com/package/history) package

```js
import createHistory from 'history/createBrowserHistory'
const history = createHistory({
  basename: '',             // The base URL 
})
```

**Comment by abz53378** [comment]
PR #50, #53 were merged, so I close it.
