### ISSUE TITLE
sidebar/navbar in CMSWrapper

### ISSUE THREAD

**Issue by abz53378** [CannerCMS/cannercms#41]
> See #39 if you have no idea what's `CMSWrapper`.

## Overview

We can pass `sidebarConfig` and `navbarConfig` to `<CMSWrapper />` to render sidebar and navbar easily.

```js
<CMSWrapper
  sidebarConfig={SidebarConfig}
  navbarConfig={NavbarConfig}
  schema={schema}
>
  <CMS />
</CMSWrapper>
```

![1](https://user-images.githubusercontent.com/8848231/43516843-54005608-95b9-11e8-9eea-c16280bbe7f0.png)

## Details

There should  be two components `<Sidebar />` and `<Navbar />`, and then `<CMSWrapper />` can just pass their config to them like below.

```js
render() {
  const {sidebarConfig, navbarConfig, children} = this.props;
  return (<Layout>
    {...}
    <Navbar {...navbarConfig} />
    {...}
    <Sidebar {...sidebarConfig} />
    {...}
  </ Layout>)
}
```

### `<Sidebar />`

Implement sidebar with antd [Sider](https://ant.design/components/layout/#components-layout-demo-side) and [Menu](https://ant.design/components/menu/)

**sidebarConfig interface**
```js

interface MenuItemConfig = {
  title: string,
  pathname: string,
  params?: {
    operation?: 'create' | 'update',
    defaultPayload?: JSONString,
    filter?: JSONString
  }
}

interface SubmenuConfig = {
  title: string,
  items: Array<MenuItemConfig>
}

interface SidebarConfig = {
  menuConfig: Array<SubmenuConfig | MenuItemConfig>
}

```

`<Sidebar />` will use `menuConfig`  to generate the antd menu. When `<MenuItem>` is clicked, it should call the `goTo` method with argument `{pathname, params}`.

> `goTo` is a method of [RouterAdaptor](https://github.com/Canner/canner/issues/40)

**menuConfig examples**
```
[{
  title: 'Posts',
  pathname: '/posts',
  params: {
    operation: 'create'
  }
  items: [...]
}]
```

[current implement in CMS](https://github.com/Canner/canner/blob/master/src/components/index.js#L121-L128)

#### render with schema
if `sidebarConfig.menuConfig` is passed as a `true` means user wants to render menu with schema, for examples:

`import schema from 'canner.schema.js'`, we will actually get a object like below,  
```js
{
  connector: Connector,
  visitors: Vistors,
  schema: DataSchema
}
``` 

We can get the data schema and transform it to menu.
```js
console.log(schema.schema);
/*
{
  info: {type: 'object', title: 'My Info', keyName: 'info',...},
  posts: {type: 'array', title: 'Posts', keyName: 'posts',...},
  users: {type: 'array', title: 'Authors', keyName: 'authors',...}
}
*/

const menuConfig = transformSchemaToMenuConfig(schema.schema);
console.log(menuConfig);

/*
[{
  title: 'My Info',
  pathname: '/info'
}, {
  title: 'Posts',
  pathname: '/posts'
}, {
  title: 'Authors',
  pathname: '/authors'
}]
*/

```

### `<Navbar />`

important with antd [Header](https://ant.design/components/layout/#components-layout-demo-top-side-2) and [Menu](https://ant.design/components/menu/#components-menu-demo-horizontal)

A navbar can be divided to three parts from left to right: logo, menu, save button:
![navbar](https://user-images.githubusercontent.com/8848231/43516827-49d244d4-95b9-11e8-9b24-f51d3d02974f.png)

And there are three properties correspond to the three parts on navbar.
**navbarConfig interface**
```js
{
  logo: string, // img url
  renderMenu: () => React.Node,
  showSaveButton: boolean
}
```

### `ChangedData`

Both `Sidebar` and `Navbar` should have different behavior when there are **unsaved** change:
- when user clicks another menu item, it should pop a confirm modal.
- the `saveButton` on navbar should have dot badge.

See [current implementation](https://github.com/Canner/canner-firebase-cms/blob/master/src/app/containers/dashboard.tsx#L65-L118)

**Comment by wwwy3y3** [comment]
@abz53378 Can we have a clearer interface of `sidebarConfig`?

For example, what properties will be included in `params`?

Furthermore, what does `renderMenu ` in `navbarConfig` do ? Does it render like antd `menu`?

**Comment by chilijung** [comment]
Agreed, I think the clearer details can help everyone to understand and give feedbacks before implementation. Also, this helps everyone on the same page.

**Comment by abz53378** [comment]
@wwwy3y3, @chilijung, @chihsuan. Updated!

**Comment by chihsuan** [comment]
PR #46 was merged. Close this issue.
