### ISSUE TITLE
override css in CMSWrapper

### ISSUE THREAD

**Issue by abz53378** [CannerCMS/cannercms#42]
## Overview

`<CMSWrapper />` should have an API to let developers override our CMS style easily

## Possible Solution

- css string
```js
<CMSWrapper
  style={`
      .antd-menu-item: {
         background: #333;
      }     
  `}
>
</CMSWrapper>
```

**Comment by wwwy3y3** [comment]
I think we should set up specific attributes to developers instead of classes like `.antd-menu-item`. We don't want to leak the implementation to developers.

For example:
```js
<CMSWrapper
  // defaultStyle stands for our default theme style
  defaultStyle={{
    primaryColor: '#FFF',
    buttonColor: '#FFF'
  }}
>
```

**Comment by chilijung** [comment]
@wwwy3y3 yeah, we have talked about that I agree with you, but we will need to discuss how it works both on platform and OSS,

- **platform**:  Should `less` files built on the server? I think less files should be automatically generated when users uploaded on CLI tools to server.

Right now our `cms-page` use bundled css files https://github.com/Canner/canner/blob/master/docs/index.html#L7

- **OSS**: As using in CMS how to take `style` props and overriding variable in` less-loader`? Right now we modify less variables from `less-loader` https://ant.design/docs/react/customize-theme#1)-Using-theme-property-(recommended-way)

cc @abz53378 @chihsuan  How do you think?

**Comment by chilijung** [comment]
On second thought, I think it's impossible to directly override attributes by passing props. It should be replace in bundlers (webpack). So another possible way is passing css (and use styled-components to overwrite styles) like @abz53378 purpose. And as our platform we should pass style variables in `canner.config.js` and compile in server.

**Comment by chilijung** [comment]
@abz53378 @wwwy3y3  I have another thought, I think we shouldn't include style props in our CMS framework, it should leave to users to setup themselves which they can easily setup their styles by reading https://ant.design/docs/react/customize-theme. (We could add a section in our document to help users to setup)

As for Canner platform, we will use `canner.config.js` and compile less files in server. I think that is the best solution how do you think.

I think we should remove `style` props, this is not a thing that related to CMS framework.

**Comment by chilijung** [comment]
@abz53378 @wwwy3y3 I'll close this issue for now. Since I think we will leave css for developers themselves.
