### ISSUE TITLE
Support chart/ dashboard in CMS

### ISSUE THREAD

**Issue by chilijung** [CannerCMS/cannercms#52]
We can consider using https://vega.github.io/vega/ syntax to support chart, and use https://github.com/kristw/react-vega/ for react port for vega lib.

## Questions

1. How to received queried data (needed data) to chart components instead of fetching all data sources at once.
   - adding a `graphql` props in the component, to allow component to have wild-card access and sending specific queries to server? instead of predefined partial data.

**Comment by wwwy3y3** [comment]
We need to design our aggregation graphql.

## Idea
For example, to create a bar chart with visitor data, you could get grouped data by:
```js
aggregateVisits {
    groupedBy {
      browser {
        keys
        values {
            count
          }
        }
      }
    }
  }
}
```

## Reference
Right now, I need to look through the community to find out if there are best practices. I'll just paste some related information I found first. There's not yet a standard spec for it.
* https://github.com/graphql/graphql-js/issues/855
* https://github.com/appbaseio/reactivesearch/issues/283
* https://github.com/blueflag/graphql-aggregate

**Comment by abz53378** [comment]
Implemented, https://github.com/Canner/canner/issues/70
