### ISSUE TITLE
Table could render differently when in create & edit mode

### ISSUE THREAD

**Issue by chilijung** [CannerCMS/cannercms#55]
Currently our popup table, no matter it is create or edit it shows with the same CMS UI, this could cause some severe limits, such as a common situation if I have a field called `createDate`. When user creates it should be editable, and in edit mode it should be disabled.

We have to think of a general interface for these kinds of usage.

**Comment by chilijung** [comment]
Actually I think we could think of a general solution, such as

```jsx
   <array>
       // something array can pass to children
       <Condition match="$mode=edit">
            // when edit mode show this 
       </Condition>
       <Condition match="$mode=create">
            // when create mode show this
       </Condition> 
   </array>
```

**Comment by chilijung** [comment]
Or we could do something like

```js
   <array>
       // something array can pass to children
       <Condition match={(mode) => {return mode === 'edit'}>
            // when edit mode show this 
       </Condition>
       <Condition match={(mode) => {return mode === 'create'}> // if match props return true show the component
            // when create mode show this
       </Condition> 
   </array>
```

**Comment by abz53378** [comment]
Here is a similar case. It takes the `data` to control the render of the children.

If we want to limit `maleConfig` **only appears** when `gender` is `male`:
  
  ```jsx
  <root>
    <object keyName="info">
      <string keyName="gender" />
      <Condition match={data => data.gender === 'male'}>
        <object keyName="maleConfig">
          {...}
        </object>
      </Condition>
    </object>
  </root>
  ```

**Comment by abz53378** [comment]
Maybe we can merge them in one tag.
```js
interface ConditionProps: {
  match: ({
    data,
    operator
  }: {
    data: any,
    operator: 'create' | 'update'
  }) => boolean,
  mode: 'disabled' | 'hidden' // default hidden
}
```

**Comment by chilijung** [comment]
I think `mode` should be more explicit like `defaultMode` or `defaultState` or `defaultValue` (just come up with some probabilities) which is better.

**Comment by wwwy3y3** [comment]
Look good to me. Kind of like the `Layout` component we're trying to make.

**Comment by abz53378** [comment]
Already implementation in https://github.com/Canner/canner/commit/1f96469cfde8ffcc6e4ca128d6486a1f0780a5d8, so I close it.
You can see the example schema [here](https://github.com/Canner/canner/blob/canary/examples/condition-fields/canner.schema.js)
