### ISSUE TITLE
Next & previous button should add padding

### ISSUE THREAD

**Issue by chilijung** [CannerCMS/cannercms#56]
Improve UI

<img width="313" alt="screen shot 2018-08-14 at 10 27 10 am" src="https://user-images.githubusercontent.com/1216029/44068461-ab60ea00-9fac-11e8-8d3d-8ae4a0421c0d.png">

**Comment by abz53378** [comment]
Fixed in cbc3f7a8de931d94fd11257e007cdc8df6a48137, so I close it.
