### ISSUE TITLE
Customize errorMessage in validation property

### ISSUE THREAD

**Issue by abz53378** [CannerCMS/cannercms#71]
We should add `errorMessage` in `validation` to let developer customize the message when the value is invalid with ajv.

```js
<number keyName="age" validation={{
  errorMessage: 'should be greater than 20 ',
  min: 20
}}/>
```

[source](https://github.com/Canner/canner/blob/canary/packages/canner/src/hocs/validation.js#L37-L59)
[docs](https://www.canner.io/docs/guides-writing-schema#validation)

**Comment by chihsuan** [comment]
Merged. Close this issue.
