### ISSUE TITLE
Image Editing in "Editor" UI

### ISSUE THREAD

**Issue by foxxxyben** [CannerCMS/cannercms#73]
I am having problems with the Rich Text Editor:

1. Editing photos has a rendering glitch and it is very difficult to get the edit icon to appear. Really should be a hover over the entire image.
2. I want to be able to change image attributes other than size, especially being able to control the wrap is quite important. [MediumEditor](https://yabwe.github.io/medium-editor/) has a great [jQuery Image Plugin](http://linkesch.com/medium-editor-insert-plugin/) that gives exactly the kind of functionality I'm looking for.

I cannot find any documentation or code letting me know how to set the options in Slate. I can't even tell if it is Canner directly, antd or some other library that wraps Slate. Do I need to wrap [MediumEditor](https://yabwe.github.io/medium-editor/) into a Customized CMS component just to make image alignment & wrapping work properly? Because from what I can tell their plugin is designed for a PHP backend, and would need to be completely refactored to make it work, so I'd rather just contribute to the existing editor to make a few simple tweaks, but I'm at a total loss of where the UI:Editor Component lives.

**Comment by chilijung** [comment]
Hi @foxxxyben `slate-editor` is still buggy now we are planning to release some fixes soon, so in latest version we relpace `quill` as our default editor https://github.com/Canner/antd-canner-components/blob/canary/packages/antd-object-editor/package.json#L16.

react-quill demo: https://zenoamaro.github.io/react-quill/

Hope this can suit your needs thanks!

**Comment by foxxxyben** [comment]
Hi @chilijung, thanks for the quick reply! As long as it includes the ability to add packages like [Quill ImageResize Module](https://www.npmjs.com/package/quill-image-resize-module) then that would be perfect. I'll be working on projects where non-technical users will be contributing content, and having those simple corner-drag and alignment options built right in is an absolute must have. Please let me know if there's any way I can help. Thanks!

**Comment by chilijung** [comment]
Agree with you that it's a really important feature, open an issue in `antd-canner-components` you could follow the progress there! https://github.com/Canner/antd-canner-components/issues/26

**Comment by chilijung** [comment]
This is added into latest editor component!
