### ISSUE TITLE
Add Enum Type

### ISSUE THREAD

**Issue by abz53378** [CannerCMS/cannercms#81]
To support [enum type](https://graphql.org/learn/schema/#enumeration-types) in graphql, we have to add an enum tag.

```js
<enum values={['A', 'B', 'C']} ui="select" uiParams={{
  options: [{
    text: 'A',
    value: 'A'
  }, {
    text: 'B',
    value: 'B'
  }, {
    text: 'C',
    value: 'C'
  }]
}}/>
```

- canner-script
  - add enum type
  - defaultUI: `select`
  - required attributes `values`
- canner-schema-loader
  - Add `enum.select: @canner/antd-string-select`, `enum.default: @canner/antd-string-select` in [componentMap](https://github.com/Canner/canner/blob/canary/packages/canner-schema-loader/src/utils.js)

**Comment by chihsuan** [comment]
Merged. Close issue.
