### ISSUE TITLE
Add the fake data when developing in local

### ISSUE THREAD

**Issue by abz53378** [CannerCMS/cannercms#85]
Add opion `fake-data` in `canner script:serve` to generate the fake data.

```
$ canner script:serve --fake-data [listLength]
```

**Comment by chilijung** [comment]
what is `listLength` mean?

**Comment by abz53378** [comment]
`listLength` lets developers decide **how many items** should be generated in their array data.

**Comment by chilijung** [comment]
I think the command could be more intuitive, cmd below is hard to recognize & extend.

```
$ canner script:serve --fake-data 3
```

**Comment by chilijung** [comment]
Since we might implement `canner script:serve` with env.

such as:

```
$ canner script:serve --env [env]
```

I think we could seperate the command. Something like.

```
$ canner script:fake --list 3 # we could add more options in the future.
```

Thoughts?

**Comment by chihsuan** [comment]
The `script:fake` looks good. I think `--list` option would still be hard to understand since it usually point to like list items. How about using `--data` or `--num` instead?

**Comment by wwwy3y3** [comment]
IMO, `--list-length` might be more specific than `data` or `num`. Adding explanation of arguments in the document would be enough.

So maybe
```sh
// fake data source
$ canner script:serve --data fake --list-length 10
// connect to production endpoint
$ canner script:serve --data prod
```

**Comment by chilijung** [comment]
or we could do, use `--env` instead of `--data`?

```
$ canner script:serve --env fake --list-length 10
```

I prefer `--env` over `--data`, how do you think?

ref: https://github.com/Canner/canner-platform/issues/2

**Comment by abz53378** [comment]
@chihsuan, thanks for your implementation of `createFakeData` (#94). Here are some feedback after using it in the project.

1. Should create the fake data of an inner array. (length = 5)
    ```
    {
      type: 'object',
      keyName: 'info',
      items: {
        hobbies: {
          type: 'array',
          items: {
            type: 'string'
          }
        }
      }
    }
    ```
    should get data like this
    ```
    {
     info: {
        hobbies: ['text1', 'text2', 'text3', 'text4', 'text5']
      }
    }
    ```
     but for now we will get an empty array of `hobbies`

2. Should create the fake data of a relation field

**Comment by chihsuan** [comment]
@abz53378:  Okay, could you give some example of relation schema and its fake data? Thanks!

**Comment by abz53378** [comment]
@chihsuan, please check out https://www.canner.io/docs/advance-component-types.html#lt-relation-gt.

**Comment by chihsuan** [comment]
@abz53378:  Since the relation type depends on the first level key of data if the schema is only included relation type, what the createFakeData should return?

**Comment by abz53378** [comment]
@chihsuan, I think returning the empty data is ok if there is no corresponding field.

## toOne example
```js
{
  posts: {
    keyName: 'posts',
    type: 'array',
    items: {
      author: {
         type: 'relation',
         relation: {
           to: 'users',        // there is no `users` fields in this schema, so just return empty toOne relation data: null
           type: 'toOne' 
         } 
      }
    }
  }
}
```
fakeData
```js
{
  posts: [{
    author: null
  }, {
    author: null
  }, ...]
}
```

## toMany example
```js
{
  posts: {
    keyName: 'posts',
    type: 'array',
    items: {
      authors: {
         type: 'relation',
         relation: {
           to: 'users',        // there is no `users` fields in this schema, so just return empty toOne relation data: null
           type: 'toMany' 
         } 
      }
    }
  }
}
```
fakeData
```js
{
  posts: [{
    authors: {} // empty object
  }, {
    authors: {}
  }, ...]
}
```

**Comment by abz53378** [comment]
Resolved.
