### ISSUE TITLE
If relationship is not assigned with value, should show nothing instead of undefined.

### ISSUE THREAD

**Issue by chilijung** [CannerCMS/cannercms#86]
<img width="1363" alt="screen shot 2018-08-29 at 2 14 23 pm" src="https://user-images.githubusercontent.com/1216029/44769058-eaa5a080-ab95-11e8-8c96-d8e399f9fdb4.png">

**Comment by abz53378** [comment]
This issue may be caused by using the wrong UI in you relation tag or an expected `uiParams.textCol` is not given.
