### ISSUE TITLE
Storage API

### ISSUE THREAD

**Issue by abz53378** [CannerCMS/cannercms#97]
## Why

For now, we take [image-service](https://github.com/Canner/image-service-config) as the storage interface. But `image-service` is actually only designed for [antd file uploader](https://ant.design/components/upload/), so it has the method `getServiceConfig` which return the `props` of antd file-uploader.

So we need a general API to let storage can integrate with different Uploader.

### In Schema
New the storage instances, and put them into `imageStorage` or `fileStorage` properties of every data tags.

```js
const imageStorage = new FIrebaseStorage(options);
const fileStorage = new ImgurStorage(options);
<root imageStorage={imageStorage} fileStorage={fileStorage}>
...
</root>
```
### In Component

Every component will receive the two storages, and upload file, listen event with the methods of the storages.

```js
upload() {
  const {imageStorage} = this.props;
  imageStorage.upload(file, options, this.handelProgress)
    .then(this.handleSuccess)
    .catch(this.handleError);
}
```

## Interface

```js
type UploadOptions = {
  filename: string,
}

type ProgressEvent = {
  percent: number,
}

abstract class Storage {
  private getUploadUrl: (file: File, filename: string) => Promise<{
     url: string
  }>;
  public upload: (file: File, options: UploadOptions, onProgress: (e: ProgressEvent) => void)
    => Promise<{link: string}>;
}
```

## The Storage List
- S3
- Firebase Client
- Firebase Admin
- Imgur

## Ref
- [image service](https://github.com/Canner/image-service-config)

**Comment by wwwy3y3** [comment]
IMO, the `publicUrl` in `getSignedUrl` is going to be meaningless if the uploading process fails, so it makes more sense we return this field at `upload` method.

Second, renaming `getSignedUrl` to `getUploadUrl` would be easier to understand.

Furthermore, I think it would be better we put `onProgress` callback to upload `method`, since we want to get the progress for individual upload, not the `storage` instance.

```js
type UploadOptions = {
  filename: string,
}

type ProgressEvent = {
  percent: number,
}

abstract class Storage {
  private getUploadUrl: (file: File, filename: string) => Promise<{
     url: string
  }>;
  public upload: (file: File, options: UploadOptions, onProgress: (e: ProgressEvent) => void)
    => Promise<{link: string}>;
}
```

**Comment by abz53378** [comment]
@chihsuan, after you finish the storages please implement the following items:
- change the property `storages` to `imageStorages` and `fileStorages` in root object of `canner-script` [ref](https://github.com/Canner/canner/blob/canary/packages/canner-script/src/models/root.js#L65)
- remove the `imageServiceConfig` property of component, using `imageStorage` and `fileStorage` instead. [ref](https://github.com/Canner/canner/blob/canary/packages/canner/src/components/Generator.js#L213)
- update `image` and `gallery` component with the property `imageStorage`.  [ref](https://github.com/Canner/antd-canner-components/blob/canary/packages/antd-object-image/src/index.js#L85) .

**Comment by abz53378** [comment]
## CannerFirebaseStorage
### The frontend Implemantation
- Developers new a CannerFirebaseStorage in their schema without any arguments and other codes.
  ```js
  const imageStorage = new CannerFirebaseStorage()
  ```
- In out CMS page, we will set `apiToken` and `appId` to the storage.
  ```js
  imageStorage.setToken(<apiToken>);
  imageStorage.setAppId(<appId>);
  ```
- When the uploading starts, call `getUploadUrl` with arguments `appId`,`apiToken`, `metaToken` first, and call `getDownloadUrl` at last.
  ```js
  getUploadUrl(file, filename, {appId, apiToken, metaToken}) {
    // call backendend getUploadUrl API
  }

  getDownloadeUrl(file, filename, {appId, apiToken, metaToken}) {
    // call backendend getDownloadUrl API
  }

  upload(file, options, onProgress) {
    const {appId, apiToken} = this;
    const metaToken = uuid();
    return this.getUploadUrl(file, options.filename, {appId, apiToken, metaToken})
      .then(({url}) => {
        // upload code 
      })
      .then(() => {
        return this.getDownloadUrl(file, options.filename, {appId, apiToken, metaToken})
      })
      //...
  }
  ```

### The backend Implemantation
Using `firebase-admin-node` or `@google-cloud/storage` to generate the urls.

**getUploadUrl example code**
```js
//  REF: https://firebase.google.com/docs/storage/admin/start
// `filename`, `metaToken`, `appId`can be got from parameters.
let firebaseApp;
try {
  // backend can get `service` with `appId`
  firebaseApp = firebaseAdmin.app(service.config.projectId);
} catch (e) {
  firebaseApp = firebaseAdmin.initializeApp({
    credential: firebaseAdmin.credential.cert(service.config.serviceAccountJson),
    databaseURL: service.config.databaseURL,
    storageBucket: service.config.storageBucket
  }, service.config.projectId);
}

const bucket = firebaseApp.storage().bucket();
const urls = await bucket.file(filename)
.createResumableUpload({
  origin: `https://<YOUR WEBSITE HOST>`,
  metadata: {
    contentType,
    metadata: {
      firebaseStorageDownloadTokens: metaToken
    }
  }
});
ctx.body = {
  url: urls[0]
};
``` 
**getDownloadUrl example code**
`filename`, `metaToken`, `appId`can be got from parameters.
```js
// get service with appId
// ...
ctx.body = {
 url: `https://firebasestorage.googleapis.com/v0/b/${service.config.storageBucket}/o/${encodeURIComponent(filename.startsWith("/") ? filename.slice(1) : filename)}?alt=media&token=${metaToken}`
}

```

@wwwy3y3, @chihsuan any advice?

**Comment by chihsuan** [comment]
@abz53378: Looks good. Just one point that I think using `getUploadUrl(file, filename, {metaToken}){}` would be simpler if we don't have any case that using it with different appId and apiToken.

**Comment by wwwy3y3** [comment]
@abz53378 shouldn't `metaToken` be generated at backend?

**Comment by abz53378** [comment]
@chihsuan, @wwwy3y3, here are some changes, how do u think?

- remove `metaToken`, and `getDownloadUrl`, storage get the `publicUrl` from the method `getUploadUrl`
- remove the third argument

```js
getUploadUrl(file, filename) {
  // call backendend getUploadUrl API
  // return {url, publicUrl}
}

upload(file, options, onProgress) {
  const metaToken = uuid();
  return this.getUploadUrl(file, options.filename)
    .then(({url, publicUrl}) => {
      // upload code 
    })
}
```

**Comment by wwwy3y3** [comment]
IMO, as response, `{uploadUrl, publicUrl}` would be better.
